// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// do_simulation
void do_simulation(const std::string csv_filename);
RcppExport SEXP experimentr_do_simulation(SEXP csv_filenameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const std::string >::type csv_filename(csv_filenameSEXP);
    do_simulation(csv_filename);
    return R_NilValue;
END_RCPP
}
