// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// do_simulation
void do_simulation(const std::string csv_filename);
RcppExport SEXP experimentr_do_simulation(SEXP csv_filenameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const std::string >::type csv_filename(csv_filenameSEXP);
    do_simulation(csv_filename);
    return R_NilValue;
END_RCPP
}
// create_data_frame_cpp
Rcpp::DataFrame create_data_frame_cpp();
RcppExport SEXP experimentr_create_data_frame_cpp() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(create_data_frame_cpp());
    return __result;
END_RCPP
}
// createTwo
DataFrame createTwo();
RcppExport SEXP experimentr_createTwo() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(createTwo());
    return __result;
END_RCPP
}
