# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

do_simulation <- function(csv_filename) {
    invisible(.Call('experimentr_do_simulation', PACKAGE = 'experimentr', csv_filename))
}

