# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
times_two_cpp <- function(x) {
    .Call('experimentr_times_two_cpp', PACKAGE = 'experimentr', x)
}

#' @export
sum_cpp <- function(x) {
    .Call('experimentr_sum_cpp', PACKAGE = 'experimentr', x)
}

#' @export
sum_cpp11 <- function(x) {
    .Call('experimentr_sum_cpp11', PACKAGE = 'experimentr', x)
}

#' @export
do_simulation <- function() {
    .Call('experimentr_do_simulation', PACKAGE = 'experimentr')
}

