# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
times_two_cpp <- function(x) {
    .Call('experimentr_times_two_cpp', PACKAGE = 'experimentr', x)
}

#' @export
sum_cpp <- function(x) {
    .Call('experimentr_sum_cpp', PACKAGE = 'experimentr', x)
}

#' @export
sum_cpp11 <- function(x) {
    .Call('experimentr_sum_cpp11', PACKAGE = 'experimentr', x)
}

do_simulation <- function(csv_filename) {
    invisible(.Call('experimentr_do_simulation', PACKAGE = 'experimentr', csv_filename))
}

create_data_frame_cpp <- function() {
    .Call('experimentr_create_data_frame_cpp', PACKAGE = 'experimentr')
}

#' @export
createTwo <- function() {
    .Call('experimentr_createTwo', PACKAGE = 'experimentr')
}

